### ISSUE TITLE
Update to NextJS 8 and hooks

### ISSUE THREAD

**Issue by dohomi** [storyblok/react-next-boilerplate#1]
Hello,
I'm just starting to learn a little bit about React and Next. The new version 8 brings in some benefits for lambda creating and the React hooks could be a nice alternative to set page settings. It would be great if this boilerplate would show some of the best examples, especially how to integrate markup or and richt text editing with links inside
Cheers

**Comment by ajmueller** [comment]
Next.js version 9 is out now, so even more reason to update this project.

**Comment by selamanse** [comment]
@dohomi I would like to try look into this.

**Comment by selamanse** [comment]
@sebgie I hope this is what you and @dohomi are looking for. I tried to understand my way into this boilerplate and integrated the whole thing to storyblok by using the mentioned tutorial in the readme: https://www.storyblok.com/tp/next-js-react-guide nextjs version is now 9.5.3.

**Comment by selamanse** [comment]
Note: can you please add hacktoberfest topic to this repo, so it can participate at Hacktoberfest? Thanks 😄 

> Ineligible Repository
> Your PR was submitted to a repository that is not participating in Hacktoberfest. Maintainers of the repository can add the > > "hacktoberfest" topic to their repository if they wish to participate.
