### ISSUE TITLE
api/preview.js missing closing curly bracket

### ISSUE THREAD

**Issue by wilbsy** [storyblok/react-next-boilerplate#14]
/pages/api/preview.js line 22 is missing a closing curly bracket.  

res.redirect(`/${slug}?${params[1]`)
should be...
res.redirect(`/${slug}?${params[1]}`)

I can submit a pull request if you'd like, since it's a super straightforward fix.
Thanks!

**Comment by lisilinhart** [comment]
Already fixed, thanks
