### ISSUE TITLE
[slug.js] and [...slug].js always load draft version

### ISSUE THREAD

**Issue by wilbsy** [storyblok/react-next-boilerplate#15]
It appears that [slug].js params.version will always be 'draft' no matter what (same goes for [...slug].js).  Unless I'm missing something, this means the draft version would always be loaded, whether in production, preview or dev (inside or outside of the SB editor).

Line 35 `version` defaults to `draft` and then is set to `draft` if `context.preview` is true.  In the useStoryblok hook, there's a conditional that will only load the bridge if in preview mode, but the draft version will still be loaded outside preview mode.  Seems fairly inconsequential for the bridge to be loaded outside of preview mode, but it would be pretty bad for the draft version to be loaded outside preview mode and outside the sb editor interface.

I realize this brings up a more complicated issue of the coordination between draft/published and preview mode cookies.  However, I feel that if it's glossed over, the confusion only increases.

Thanks!  :)

**Comment by lisilinhart** [comment]
The parameter on Line 36 in `[...slug].js` is only set to `draft`, because a lot of people start the tutorial with a new space, that doesn't have published content yet. Later on, you would of course always want to load `published`, if you are not inside the preview mode.
